#!/usr/bin/env python3
'''open a window'''
from PyQt5.QtWidgets import QApplication
from pychummer.model import Database
from pychummer.view import CharacterListPanel
import sys

def main():
    '''Start a new pychummer application'''
    app = QApplication([])
    database = Database()

    view = CharacterListPanel(database=database)

    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
